spring.application.name=aqar-payment-backend

spring.datasource.url=jdbc:mysql://localhost:3306/aqar
spring.datasource.username=root
spring.datasource.password=zezopop2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.servlet.context-path=/api/payment
server.port=8089

# JWT
jwt.secret=jwt-secret-for-aqar-backend-and-all-microservices
jwt.expiration.ms=86400000
jwt.customer-issuer=aqar-customer
jwt.admin-issuer=aqar-admin

customer.base-url=http://localhost:8085/api/customer


paymob.base-url=https://accept.paymob.com
paymob.secret-key=egy_sk_test_bca9499a7519916f4de0082a0c524924b687667b44fca2de40f2fad88cef9626
paymob.public-key=egy_pk_test_34sbYMh5UTPqcrziB1J4PeQ9rXnfuAj8
paymob.integration-id=5174253
paymob.hmac-secret=9626403CEB53EAFFABBB92B51E176ABC
paymob.notification-url=https://exampKYqoksRbHyzOMN990y5sE2A1qWIorsHBSOPZ1oCyle.ngrok-free.app/api/paymob/webhook
paymob.redirection-url=https://wizard.paymob.com/webhooks/paymob/dd6cc54a10b37e236bf92fc278e0f16e14cadd23d205f6db


fawaterk.base-url=https://staging.fawaterk.com
fawaterk.client-id=a2d6d510-e00f-493f-85a5-43d78930079f
fawaterk.client-secret=fTQgkUjzoJHTuvM39qot0sxIQdin0AkL8baG3aSE
fawaterk.hash-api-key=063914c1adbf1c328d051d501f1b20aef137cecf04cbd915fd