spring.application.name=aqar-payment-backend

spring.datasource.url=jdbc:mysql://localhost:3306/aqar
spring.datasource.username=root
spring.datasource.password=zezopop2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.servlet.context-path=/api/payment
server.port=8088

# JWT
jwt.secret=jwt-secret-for-admin-backend-ndjksncsdkjdbnv
jwt.expiration.ms=86400000


paymob.base-url=https://accept.paymob.com
paymob.secret-key=egy_sk_test_bca9499a7519916f4de0082a0c524924b687667b44fca2de40f2fad88cef9626
paymob.public-key=egy_pk_test_34sbYMh5UTPqcrziB1J4PeQ9rXnfuAj8
paymob.integration-id=5174253
paymob.hmac-secret=9626403CEB53EAFFABBB92B51E176ABC
paymob.notification-url=https://exampKYqoksRbHyzOMN990y5sE2A1qWIorsHBSOPZ1oCyle.ngrok-free.app/api/paymob/webhook
paymob.redirection-url=https://wizard.paymob.com/webhooks/paymob/dd6cc54a10b37e236bf92fc278e0f16e14cadd23d205f6db


fawaterk.client-secret=McCIkWpPs0ii55bIV3pzZ3nQnlDOMftcpv05TWRb
fawaterk.client-id=a2d24b61-7ebb-4c33-abed-de64dda456da
fawaterk.token-url=https://app.fawaterk.com/oauth/token
fawaterk.hash-api-key=6d4a8f89cef068d34e123e57867efd80bd870513255ba5430a
fawaterk.hmac-secret=307f4a25d6d32aed2908382098db1ac60147b2d501b5dd0d1d23681d1234e434